package com.pompomhills.intelligence.meta;

public enum MetaCapability {
  META_FACEBOOK_ANALYTICS_READ,
  META_INSTAGRAM_ANALYTICS_READ,
  META_FACEBOOK_COMMENTS_READ,
  META_INSTAGRAM_COMMENTS_READ,
  META_FACEBOOK_COMMENT_REPLY,
  META_INSTAGRAM_COMMENT_REPLY,
  META_FACEBOOK_PUBLISH,
  META_INSTAGRAM_PUBLISH
}
