import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: 'overview', loadComponent: () => import('./pages/overview.page').then((m) => m.OverviewPage), title: 'Overview · Pompom CI' },
  { path: 'render', loadComponent: () => import('./pages/render-dashboard.page').then((m) => m.RenderDashboardPage), title: 'Render Pipeline · Pompom CI' },
  { path: 'rule-governance', loadComponent: () => import('./pages/rule-governance.page').then((m) => m.RuleGovernancePage), title: 'Rule Governance · Pompom CI' },
  { path: 'quality/detail', loadComponent: () => import('./pages/quality-validator/quality-validator.component').then((m) => m.QualityValidatorComponent), title: 'Prompt Detail · Pompom CI' },
  { path: 'quality/new', loadComponent: () => import('./pages/creative-studio.page').then((m) => m.CreativeStudioPage), title: 'Create New Video · Pompom CI' },
  { path: 'quality', loadComponent: () => import('./pages/quality-validator/quality-validator.component').then((m) => m.QualityValidatorComponent), title: 'Prompt Quality · Pompom CI' },
  { path: 'videos', loadComponent: () => import('./pages/video-library.page').then((m) => m.VideoLibraryPage), title: 'Video Library · Pompom CI' },
  { path: 'videos/workbench', loadComponent: () => import('./pages/video-analysis-workbench.page').then((m) => m.VideoAnalysisWorkbenchPage), title: 'Analysis Workbench · Pompom CI' },
  { path: 'videos/detail', loadComponent: () => import('./pages/video-detail.page').then((m) => m.VideoDetailPage), title: 'Video Review Studio · Pompom CI' },
  { path: 'videos/:id', loadComponent: () => import('./pages/video-detail.page').then((m) => m.VideoDetailPage), title: 'Video Detail · Pompom CI' },
  { path: 'characters', loadComponent: () => import('./pages/character-lab.page').then((m) => m.CharacterLabPage), title: 'Character Lab · Pompom CI' },
  { path: 'predictions', loadComponent: () => import('./pages/predictions.page').then((m) => m.PredictionsPage), title: 'Predictions · Pompom CI' },
  { path: 'import', loadComponent: () => import('./pages/import-data.page').then((m) => m.ImportDataPage), title: 'Import Data · Pompom CI' },
  { path: 'experiments', loadComponent: () => import('./pages/experiments.page').then((m) => m.ExperimentsPage), title: 'Experiments · Pompom CI' },
  { path: 'test-planner', loadComponent: () => import('./pages/test-planner.page').then((m) => m.TestPlannerPage), title: 'Test Planner · Pompom CI' },
  { path: 'performance', loadComponent: () => import('./pages/performance.page').then((m) => m.PerformancePage), title: 'Performance · Pompom CI' },
  { path: 'reliability', loadComponent: () => import('./pages/reliability.page').then((m) => m.ReliabilityPage), title: 'Model Reliability · Pompom CI' },
  { path: 'research', loadComponent: () => import('./pages/reach-further-research.page').then((m) => m.ReachFurtherResearchPage), title: 'Reach Further Research · Pompom CI' },
  { path: 'meta/connection', loadComponent: () => import('./pages/meta-connection.page').then((m) => m.MetaConnectionPage), title: 'Meta Connection · Pompom CI' },
  { path: 'meta/reels', loadComponent: () => import('./pages/meta-reels.page').then((m) => m.MetaReelsPage), title: 'Instagram Reels · Pompom CI' },
  { path: 'meta/reels/:mediaId', loadComponent: () => import('./pages/meta-reel-analytics.page').then((m) => m.MetaReelAnalyticsPage), title: 'Reel Analytics · Pompom CI' },
  { path: 'models', loadComponent: () => import('./pages/models.page').then((m) => m.ModelsPage), title: 'Model Versions · Pompom CI' },
  { path: 'operations', loadComponent: () => import('./pages/operations.page').then((m) => m.OperationsPage), title: 'Operations · Pompom CI' },
  { path: '', pathMatch: 'full', redirectTo: 'overview' },
  { path: '**', redirectTo: 'overview' },
];
