package com.pompom.ruleset.domain;

import io.hypersistence.utils.hibernate.type.json.JsonBinaryType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Type;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * Candidate rule entity.
 * Generated by learning engine when correlations are detected.
 * Requires human review before becoming active rule.
 */
@Entity
@Table(name = "candidate_rules")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CandidateRule {
    
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;
    
    @Column(name = "rule_code", length = 50)
    private String ruleCode;
    
    @Column(name = "name", length = 255)
    private String name;
    
    @Enumerated(EnumType.STRING)
    @Column(name = "category", length = 30)
    private Rule.RuleCategory category;
    
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
    
    // Correlation evidence
    @Column(name = "correlation_metric", length = 100)
    private String correlationMetric;
    
    @Column(name = "correlation_coefficient", precision = 5, scale = 4)
    private BigDecimal correlationCoefficient;
    
    @Column(name = "p_value", precision = 10, scale = 8)
    private BigDecimal pValue;
    
    @Column(name = "sample_size")
    private Integer sampleSize;
    
    @Type(JsonBinaryType.class)
    @Column(name = "example_video_ids", columnDefinition = "jsonb")
    private List<String> exampleVideoIds;
    
    // Review status
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    @Builder.Default
    private CandidateStatus status = CandidateStatus.PENDING_REVIEW;
    
    @Column(name = "reviewed_by", length = 100)
    private String reviewedBy;
    
    @Column(name = "reviewed_at")
    private Instant reviewedAt;
    
    @Column(name = "rejection_reason", columnDefinition = "TEXT")
    private String rejectionReason;
    
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt = Instant.now();
    
    public enum CandidateStatus {
        PENDING_REVIEW,  // Awaiting human review
        APPROVED,        // Approved, converted to active rule
        REJECTED         // Rejected, will not be activated
    }
    
    /**
     * Approve this candidate rule.
     */
    public void approve(String reviewer) {
        this.status = CandidateStatus.APPROVED;
        this.reviewedBy = reviewer;
        this.reviewedAt = Instant.now();
    }
    
    /**
     * Reject this candidate rule.
     */
    public void reject(String reviewer, String reason) {
        this.status = CandidateStatus.REJECTED;
        this.reviewedBy = reviewer;
        this.reviewedAt = Instant.now();
        this.rejectionReason = reason;
    }
}
